Switch to AST-style zfs-auto-snapshot.slackbuild
This contains source download logic that was not present in the
previous design.

diff --git a/zfs-auto-snapshot/zfs-auto-snapshot.SlackBuild b/zfs-auto-snapshot/zfs-auto-snapshot.SlackBuild
--- a/zfs-auto-snapshot/zfs-auto-snapshot.SlackBuild
+++ b/zfs-auto-snapshot/zfs-auto-snapshot.SlackBuild
@@ -1,108 +1,221 @@
-#!/bin/sh -e
+#!/bin/sh
+# Generated by Alien's SlackBuild Toolkit: http://slackware.com/~alien/AST
+# Copyright 2009, 2010, 2011, 2012  Eric Hameleers, Eindhoven, Netherlands
+# Copyright 2012  Ron Parker <rdparker@gmail.com>
+# All rights reserved.
 #
-# Ron Parker 2012/12/11
+#   Permission to use, copy, modify, and distribute this software for
+#   any purpose with or without fee is hereby granted, provided that
+#   the above copyright notice and this permission notice appear in all
+#   copies.
+#
+#   THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
+#   WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
+#   IN NO EVENT SHALL THE AUTHORS AND COPYRIGHT HOLDERS AND THEIR
+#   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+#   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+#   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
+#   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+#   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
+#   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
+#   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
+#   SUCH DAMAGE.
+# -----------------------------------------------------------------------------
+#
+# Slackware SlackBuild script
+# ===========================
+# By:          Ron Parker <rdparker@gmail.com>
+# For:         zfs-auto-snapshot
+# Descr:       zfs-auto-snapshot (Take automatic ZFS snapshots)
+# URL:         https://github.com/dajhorn/zfs-auto-snapshot
+# Needs:
+# Changelog:
+# 1.0.8-1:     11/Dec/2012 Ron Parker <rdparker@gmail.com>
+#              * Initial build.
+# 1.0.8-2:     11/Dec/2012 Ron Parker <rdparker@gmail.com>
+#              * Add a "frequent" cronjob
+# 1.0.8-3:     27/Dec/2012 by Ron Parker <rdparker@gmail.com>
+#              * Switch to a AST-style slackbuild
+#
+# Run 'sh zfs-auto-snapshot.SlackBuild' to build a Slackware package.
+# The package (.txz) and .txt file as well as build logs are created in /tmp .
+# Install it using 'installpkg'.
+#
+# -----------------------------------------------------------------------------
 
-# Set initial variables
-CWD=$(pwd)
-if [ "$TMP" = "" ]; then
-  TMP=/tmp
+# Set initial variables:
+
+PRGNAM=zfs-auto-snapshot
+VERSION=${VERSION:-1.0.8}
+BUILD=${BUILD:-3}
+# 'make' can run jobs in parallel for added speed. The number should be higher
+# than the number of cores/virtual CPU's in your system:
+NUMJOBS=${NUMJOBS:" -j9 "}
+# The TAG is a unique identifier for all your Slackware packages.
+# Use your initials as the value for TAG for instance.
+TAG=${TAG:-_rdp}
+
+# This covers most filenames you'd want as documentation. Change if needed.
+DOCS="COPYING README"
+
+# Where do we look for sources?
+SRCDIR=$(cd $(dirname $0); pwd)
+
+# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
+TMP=${TMP:-/tmp/build}
+PKG=$TMP/package-$PRGNAM
+OUTPUT=${OUTPUT:-/tmp}
+
+# Input URL: http://github.com/downloads/zfsonlinux/zfs/zfs-0.6.0-rc12.tar.gz
+SOURCE="$SRCDIR/${VERSION}.tar.gz"
+SRCURL="https://github.com/dajhorn/${PRGNAM}/archive/upstream/${VERSION}.tar.gz"
+
+
+##
+## --- with a little luck, you won't have to edit below this point --- ##
+##
+
+# Automatically determine the architecture we're building on:
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) export ARCH=i486 ;;
+    arm*) export ARCH=arm ;;
+    # Unless $ARCH is already set, use uname -m for all other archs:
+       *) export ARCH=$( uname -m ) ;;
+  esac
 fi
 
-# The version which appears in the application's filename
-VERSION=1.0.8
+case "$ARCH" in
+  i486)   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+          SLKLDFLAGS=""; LIBDIRSUFFIX=""
+          ;;
+  x86_64) SLKCFLAGS="-O2 -fPIC"
+          SLKLDFLAGS="-L/usr/lib64"; LIBDIRSUFFIX="64"
+          ;;
+  *)      SLKCFLAGS="-O2"
+          SLKLDFLAGS=""; LIBDIRSUFFIX=""
+          ;;
+esac
 
-# If the version conflicts with the Slackware package standard,
-# You can set the PKG_VERSION to something other than VERSION.
-# The dash character ("-") is not allowed in the VERSION string
-PKG_VERSION=1.0.8 # the version which appears in the package name.
+# Exit the script on errors:
+set -e
+trap 'echo "$0 FAILED at line ${LINENO}" | tee $OUTPUT/error-${PRGNAM}.log' ERR
+# Catch unitialized variables:
+set -u
+P1=${1:-1}
 
-ARCH=${ARCH:-x86_64} # the architecture on which you want to build your package
+# Save old umask and set to 0022:
+_UMASK_=$(umask)
+umask 0022
 
-# First digit is the build number, which specifies how many times it
-# has been built.  Second string is the short form of the authors
-# name, typically three initials.
-BUILD=${BUILD:-2_rdp}
+# Create working directories:
+mkdir -p $OUTPUT          # place for the package to be saved
+mkdir -p $TMP/tmp-$PRGNAM # location to build the source
+mkdir -p $PKG             # place for the package to be built
+rm -rf $PKG/*             # always erase old package's contents
+rm -rf $TMP/tmp-$PRGNAM/* # remove the remnants of previous build
+rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PRGNAM.log
+                          # remove old log files
 
-# The application's name
-APP=zfs-auto-snapshot
-
-# The installation directory of the package (where its actual
-# directory structure whill be created).
-PKG=$TMP/package-$APP
-
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+# Source file availability:
+if ! [ -f ${SOURCE} ]; then
+  echo "Source '$(basename ${SOURCE})' not available yet..."
+  # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
+  [ -w "$SRCDIR" ] || SOURCE="$OUTPUT/$(basename $SOURCE)"
+  if [ -f ${SOURCE} ]; then echo "Ah, found it!"; continue; fi
+  if ! [ "x${SRCURL}" == "x" ]; then
+    echo "Will download file to $(dirname $SOURCE)"
+    wget -nv -T 20 -O "${SOURCE}" "${SRCURL}" || true
+    if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+      echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+      mv -f "${SOURCE}" "${SOURCE}".FAIL
+      exit 1
+    fi
+  else
+    echo "File '$(basename ${SOURCE})' not available... aborting the build."
+    exit 1
+  fi
 fi
 
-# Delete the leftover directories if they exist (due to a previous build)
-# and (re)create the packaging directory
-rm -rf $PKG
-mkdir -p $TMP $PKG
-rm -rf $TMP/$APP-$VERSION
+if [ "$P1" == "--download" ]; then
+  echo "Download complete."
+  exit 0
+fi
 
-# Change to the TMP directory
-cd $TMP || exit 1
+# --- PACKAGE BUILDING ---
 
-# Extract the application source in TMP
-# Note: if your application comes as a tar.bz2, you need tar -jxvf
-tar -zxvf $CWD/$VERSION.tar.gz || exit 1
+echo "++"
+echo "|| $PRGNAM-$VERSION"
+echo "++"
 
-# Change to the application source directory
-cd $APP-upstream-$VERSION || exit 1
+# Explode the package framework:
+if [ -f $SRCDIR/_$PRGNAM.tar.gz ]; then
+  cd $PKG
+  explodepkg $SRCDIR/_$PRGNAM.tar.gz
+  cd -
+fi
 
-# Change the ownership and permissions if necessary
-# This may not be needed in some source tarballs, but it never hurts
+cd $TMP/tmp-$PRGNAM
+echo "Extracting the source archive(s) for $PRGNAM..."
+if $(file ${SOURCE} | grep -qi ": 7-zip"); then
+  7za x ${SOURCE}
+elif $(file ${SOURCE} | grep -qi ": zip"); then
+  unzip ${SOURCE}
+else
+  tar -xvf ${SOURCE}
+fi
+cd ${PRGNAM}-upstream-${VERSION}
 chown -R root:root .
-chmod -R u+w,go+r-w,a-s .
+chmod -R u+w,go+r-w,a+X-s .
 
-# compile the source, but exit if anything goes wrong
-make || exit $?
+echo Building ...
+make $NUMJOBS 2>&1 | tee $OUTPUT/make-${PRGNAM}.log
+make DESTDIR=$PKG install 2>&1 | tee $OUTPUT/install-${PRGNAM}.log
 
-# Install everything in the package directory, but exit if anything goes wrong
-make install DESTDIR=$PKG || exit $?
-install $CWD/zfs-auto-snapshot.cron.frequent \
+# Add the frequent cronjob file
+install $SRCDIR/zfs-auto-snapshot.cron.frequent \
     $PKG/etc/cron.d/zfs-auto-snapshot || exit $?
 
-# Create a directory for documentation
-mkdir -p $PKG/usr/doc/$APP-$VERSION
 
-# Copy documentation to the docs directory and fix permissions
-cp -a README $PKG/usr/doc/$APP-$VERSION
-find $PKG/usr/doc/$APP-$VERSION -type f -exec chmod 644 {} \;
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION || true
+cat $SRCDIR/$(basename $0) > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
+find $PKG/usr/doc -type f -exec chmod 644 {} \;
 
-cat $CWD/$APP.SlackBuild > $PKG/usr/doc/$APP-$VERSION/$APP.SlackBuild
-
-# Create the ./install directory and copy the slack-desc into it
-mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
-
-# Add doinst.sh to package (if it exists)
-if [ -e $CWD/doinst.sh.gz ]; then
-  zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
-fi
-
-# Strip some libraries and binaries
-find $PKG | xargs file | egrep "executable|shared object" | grep ELF | \
-    cut -f 1 -d : | xargs --no-run-if-empty strip --strip-unneeded 2> /dev/null
-
-# Compress man pages if they exist
+# Compress the man page(s):
 if [ -d $PKG/usr/man ]; then
-    ( cd $PKG/usr/man
-	find . -type f -exec gzip -9 {} \;
-	for i in $(find . -type l) ; do
-	    ln -s $(readlink $i).gz $i.gz ; rm $i
-	done
-    )
+  find $PKG/usr/man -type f -name "*.?" -exec gzip -9f {} \;
+  for i in $(find $PKG/usr/man -type l -name "*.?") ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 fi
 
-# Compress info pages if they exist (and remove the dir file)
+# Compress info pages and remove the package's dir file:
 if [ -d $PKG/usr/info ]; then
-    gzip -9 $PKG/usr/info/*.info
-    rm -f $PKG/usr/info/dir
+  rm -f $PKG/usr/info/dir
+  gzip -9f $PKG/usr/info/*.info*
+  # If any info files are present, consider adding this to a doinst.sh:
+  # chroot . install-info /usr/info/XXXXX.info.gz /usr/info/dir 2> /dev/null
 fi
 
-# Build the package
+# Strip binaries (if any):
+find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+# Add a package description:
+mkdir -p $PKG/install
+cat $SRCDIR/slack-desc > $PKG/install/slack-desc
+if [ -f $SRCDIR/doinst.sh ]; then
+  cat $SRCDIR/doinst.sh >> $PKG/install/doinst.sh
+fi
+
+# Build the package:
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/$APP-$PKG_VERSION-$ARCH-$BUILD.txz
+makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} 2>&1 | tee $OUTPUT/makepkg-${PRGNAM}.log
+cd $OUTPUT
+md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz}.md5
+cd -
+cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txt
+
+# Restore the original umask:
+umask ${_UMASK_}
