Work on statically linking CFEngine

diff --git a/cfengine/cfengine.SlackBuild b/cfengine/cfengine.SlackBuild
--- a/cfengine/cfengine.SlackBuild
+++ b/cfengine/cfengine.SlackBuild
@@ -29,8 +29,10 @@
 # URL:         http://cfengine.com
 # Needs:
 # Changelog:
-# 3.4.1-2:     29/Nov/2012 by Ron Parker <rdparker@gmail.com>
+# 3.4.1-1:     29/Nov/2012 by Ron Parker <rdparker@gmail.com>
 #              * Initial build.
+# 3.4.1-2:     13/Dec/2012 by Ron Parker <rdparker@gmail.com>
+#              * Statically link cfengine.
 #
 # Run 'sh cfengine.SlackBuild' to build a Slackware package.
 # The package (.txz) and .txt file as well as build logs are created in /tmp .
@@ -42,7 +44,7 @@
 
 PRGNAM=cfengine
 VERSION=${VERSION:-3.4.1}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 # 'make' can run jobs in parallel for added speed. The number should be higher
 # than the number of cores/virtual CPU's in your system:
 NUMJOBS=${NUMJOBS:" -j9 "}
@@ -62,9 +64,15 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 # Input URL: http://cfengine.com/source-code/download?file=cfengine-3.4.1.tar.gz
-SOURCE="$SRCDIR/${PRGNAM}-${VERSION}.tar.gz"
-SRCURL="http://cfengine.com/source-code/download?file=${PRGNAM}-${VERSION}.tar.gz"
+SOURCE[0]="$SRCDIR/${PRGNAM}-${VERSION}.tar.gz"
+SRCURL[0]="http://cfengine.com/source-code/download?file=${PRGNAM}-${VERSION}.tar.gz"
 
+# A static liblzma is needed
+SOURCE[1]="$SRCDIR/xz.SlackBuild"
+SRCURL[1]="http://mirrors.slackware.com/slackware/slackware-14.0/source/a/xz/xz.SlackBuild"
+
+SOURCE[2]="$SRCDIR/xz-5.0.4.tar.bz2"
+SRCURL[2]="http://mirrors.slackware.com/slackware/slackware-14.0/source/a/xz/xz-5.0.4.tar.bz2"
 
 ##
 ## --- with a little luck, you won't have to edit below this point --- ##
@@ -82,13 +90,13 @@ fi
 
 case "$ARCH" in
   i486)   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
-          SLKLDFLAGS=""; LIBDIRSUFFIX=""
+          SLKLDFLAGS="--static"; LIBDIRSUFFIX=""
           ;;
   x86_64) SLKCFLAGS="-O2 -fPIC"
-          SLKLDFLAGS="-L/usr/lib64"; LIBDIRSUFFIX="64"
+          SLKLDFLAGS="-L/usr/lib64 --static"; LIBDIRSUFFIX="64"
           ;;
   *)      SLKCFLAGS="-O2"
-          SLKLDFLAGS=""; LIBDIRSUFFIX=""
+          SLKLDFLAGS="--static"; LIBDIRSUFFIX=""
           ;;
 esac
 
@@ -113,24 +121,26 @@ rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PRGNAM.log
                           # remove old log files
 
 # Source file availability:
-if ! [ -f ${SOURCE} ]; then
-  echo "Source '$(basename ${SOURCE})' not available yet..."
-  # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
-  [ -w "$SRCDIR" ] || SOURCE="$OUTPUT/$(basename $SOURCE)"
-  if [ -f ${SOURCE} ]; then echo "Ah, found it!"; continue; fi
-  if ! [ "x${SRCURL}" == "x" ]; then
-    echo "Will download file to $(dirname $SOURCE)"
-    wget -nv -T 20 -O "${SOURCE}" "${SRCURL}" || true
-    if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
-      echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
-      mv -f "${SOURCE}" "${SOURCE}".FAIL
+for (( i = 0; i < ${#SOURCE[*]}; i++ )) ; do
+  if ! [ -f ${SOURCE[$i]} ]; then
+    echo "Source '$(basename ${SOURCE[$i]})' not available yet..."
+    # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
+    [ -w "$SRCDIR" ] || SOURCE[$i]="$OUTPUT/$(basename ${SOURCE[$i]})"
+    if [ -f ${SOURCE[$i]} ]; then echo "Ah, found it!"; continue; fi
+    if ! [ "x${SRCURL[$i]}" == "x" ]; then
+      echo "Will download file to $(dirname $SOURCE[$i])"
+      wget -nv -T 20 -O "${SOURCE[$i]}" "${SRCURL[$i]}" || true
+      if [ $? -ne 0 -o ! -s "${SOURCE[$i]}" ]; then
+        echo "Fail to download '$(basename ${SOURCE[$i]})'. Aborting the build."
+        mv -f "${SOURCE[$i]}" "${SOURCE[$i]}".FAIL
+        exit 1
+      fi
+    else
+      echo "File '$(basename ${SOURCE[$i]})' not available. Aborting the build."
       exit 1
     fi
-  else
-    echo "File '$(basename ${SOURCE})' not available... aborting the build."
-    exit 1
   fi
-fi
+done
 
 if [ "$P1" == "--download" ]; then
   echo "Download complete."
@@ -152,30 +162,40 @@ fi
 
 cd $TMP/tmp-$PRGNAM
 echo "Extracting the source archive(s) for $PRGNAM..."
-if $(file ${SOURCE} | grep -qi ": 7-zip"); then
-  7za x ${SOURCE}
-elif $(file ${SOURCE} | grep -qi ": zip"); then
-  unzip ${SOURCE}
+if $(file ${SOURCE[0]} | grep -qi ": 7-zip"); then
+  7za x ${SOURCE[0]}
+elif $(file ${SOURCE[0]} | grep -qi ": zip"); then
+  unzip ${SOURCE[0]}
 else
-  tar -xvf ${SOURCE}
+  tar -xvf ${SOURCE[0]}
 fi
 cd ${PRGNAM}-${VERSION}
+cp ${SOURCE[1]} .
+cp ${SOURCE[2]} .
 chown -R root:root .
 chmod -R u+w,go+r-w,a+X-s .
 
+echo "Building liblzma.a for $PRGNAM..."
+sed -i '
+/^rm .*xz-tmp/d;
+/^mv.*xz-tmp/d;
+s/enable\(-shared\)/disable\1/;
+s/disable\(-static\)/enable\1/' xz.SlackBuild
+XZ_DIR=$(pwd)/xz-static
+TMP=$XZ_DIR sh xz.SlackBuild
+
 echo Building ...
+sed -i '/LIBS=""/d' m4/cf3_with_library.m4
+autoconf
+LIBS="$XZ_DIR/package-xz/usr/lib${LIBDIRSUFFIX}/liblzma.a -lbz2 -lz -lm -ldl" \
 LDFLAGS="$SLKLDFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/var/cfengine \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --localstatedir=/var \
   --sysconfdir=/etc \
-  --mandir=/usr/man \
-  --docdir=/usr/doc/$PRGNAM-$VERSION \
-  --enable-shared \
-  --disable-static \
+  --enable-static \
+  --disable-shared \
   --program-prefix= \
   --program-suffix= \
   --build=$ARCH-slackware-linux \
